### ISSUE TITLE
Using random() instead of arc4random_uniform() ?

### ISSUE THREAD

**Issue by hzeller** [cgorringe/ft-demos#1]
The `arc4random_uniform(int range)` function seems to be specialized for a particular platform, so this code does not compile without modifications.

Would it hurt to replace it with calls to `random() % range` ? The `random()` function might not be the best ever random generator, but it is available in all standard C libraries (`#include <stdlib.h>`)

(or just some simple file with an

```
  inline int rangedRandom(int range) {
#ifdef MACOS
   return arc4random_uniform(range);
#else
    return random() % range;
#endif
  }
```

)

**Comment by cgorringe** [comment]
Thanks for testing this on a non-mac system!  Since we don't really care about the quality of the random function, I replaced them all with random(), so it should work everywhere now.

**Comment by hzeller** [comment]
Wonderful, thanks! It compiles now without changes.
