### ISSUE TITLE
blur has the last column black

### ISSUE THREAD

**Issue by hzeller** [cgorringe/ft-demos#5]
In 'blur', the last column is always black. This is probably due to the

```
  // draw black border & blur on every frame
```

Which is not quite clear to me why that is. However, if I remove the black box, then there is some artifact on the right (looks like pixel are collecting) - so there is presumably a reason for this.

However, it would be good to fill the screen fully. Should this just be hacked with `opt_width+=1;` somewhere ? :)

**Comment by cgorringe** [comment]
Yep, there's a reason.  The blur effect is basically taking an average of 4 pixels (2x2 grid) and storing the average in the upper-left pixel.  This is what causes the blur to appear to move up and to the left.  Now the pixel values are 0-255, which is an index into a color lookup table or palette. So how do you calculate the right and bottom edges if you can't read a value beyond the edge? We must either clear them with 0-pixels, or else use a screen buffer that is (width+1) x (height+1) and store 0-pixels in the off-screen edge.

**Comment by hzeller** [comment]
Ah, I see. Sweet algorithm.
So yeah, we can silently just increase our buffer by 1 in both directions. and then only copy the visible part into the framebuffer to send.

Or, even simpler, but hackier, just pretend to always have a slightly bigger framebuffer than what is given on the command line (e.g. 46x36) - the FlaschenTaschen installation does not care in full screen mode it only shows full screen.

But of course, this doesn't work well when we want to show blur in a frame in the middle, then it is oddly too large ...
